### ISSUE TITLE
glsl-js donation

### ISSUE THREAD

**Issue by dy** [stackgl/contributing#31]
@hughsk @chrisdickinson @mattdesl @mikolalysenko hello!

I’m finishing [glsl → js compiler](https://github.com/dfcreative/glsl-js), it is going to be a RC soon, the most significant part is ready.
I would like to donate this project to stack-gl, as it fits here. Could you please have a look and tell what are necessary enhancements.

[Demo is coming](https://github.com/dfcreative/glsl-js/issues/19).

Looking forward.

Thanks!

**Comment by dy** [comment]
Maybe call it _glsl-compiler_ to be in row with _glsl-parser_, _glsl-deparser_ and _glsl-tokenizer_?

**Comment by hughsk** [comment]
Hey @dfcreative! That'd be awesome, thanks :D Maybe _glsl-transpiler_ would work best? Let me know if you'd like us to add you to the org and we can transfer it over on GitHub/npm when you're ready!

**Comment by dy** [comment]
I’m ready to transfer as soon as you authorize me).
I’m thinking that `glsl-transpiler` is a good name, considering that there is [glsl.js](https://www.npmjs.com/package/glsl) already doing similarly the same, so avoiding name confusion is good. There is no direct rigid dependents of this package, so changing the name should not be the case.

**Comment by hughsk** [comment]
:tada: done!
