### ISSUE TITLE
gl-skybox

### ISSUE THREAD

**Issue by hughsk** [stackgl/contributing#4]
Would be nice to have a `gl-skybox` package that can [take a cubemap texture and render it behind the main scene](http://antongerdelan.net/opengl/cubemaps.html).

More expensive, but rendering the sky in a shader as demonstrated [here](http://codeflow.org/entries/2011/apr/13/advanced-webgl-part-2-sky-rendering/) would also be super nice.

**Comment by wwwtyro** [comment]
https://github.com/wwwtyro/gl-skybox for the first part

**Comment by wwwtyro** [comment]
https://github.com/wwwtyro/glsl-atmosphere for the second part :tada:

I'm gonna close this now, please reopen if you think it's not complete.
